version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
